web:
    image: shincoder/homestead:php7.1
    restart: unless-stopped
    ports:
        - "80:80" # web
        - "22:22" # ssh
    volumes:
        - f:/works/.composer:/home/homestead/.composer # composer caching
        - f:/works/.gitconfig:/home/homestead/.gitconfig # Git configuration ( access alias && config )
        - f:/works/.ssh:/home/homestead/.ssh # Ssh keys for easy deployment inside the container
        - f:/works/web:/apps # all apps
        - f:/works/nginx/sites-available:/etc/nginx/sites-available # nginx sites ( in case you recreate the container )
        - f:/works/nginx/sites-enabled:/etc/nginx/sites-enabled # nginx sites ( in case you recreate the container )
        - f:/works/nginx/ssl:/etc/nginx/ssl
    links:
        - mysql

mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: 'root'
    volumes:
        - f:/docker/mysql:/var/lib/mysql